package com.pikume.back.user.auth.application.exception;

public enum EmailVerificationFailure {
    INVALID_REQUEST, INVALID_EMAIL, VERIFICATION_INVALID, VERIFICATION_ALREADY_COMPLETED,
    CODE_EXPIRED, CODE_MISMATCH, ATTEMPTS_EXHAUSTED, RATE_LIMITED, EMAIL_SEND_FAILED,
    TOKEN_INVALID, TOKEN_EXPIRED, TOKEN_ALREADY_USED
}
