package com.pikume.back.user.auth.application.exception;

public enum SignupFailure {
    SIGNUP_DISABLED, LEGACY_SIGNUP_DISABLED, INVALID_REQUEST, INVALID_EMAIL, INVALID_PASSWORD,
    PROOF_INVALID, PROOF_EXPIRED, PROOF_ALREADY_USED, FLOW_MISMATCH,
    CHALLENGE_INVALID, CODE_EXPIRED, CODE_MISMATCH, ATTEMPTS_EXHAUSTED, RATE_LIMITED, EMAIL_SEND_FAILED,
    AGREEMENTS_REQUIRED, AGREEMENT_VERSION_MISMATCH, EMAIL_ALREADY_REGISTERED,
    USER_UNAVAILABLE, DEFAULT_CHARACTER_UNAVAILABLE, NICKNAME_COLLISION
}
